/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a recruiter account */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a token */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the caller's jobs, newest first */
        get: operations["listJobs"];
        put?: never;
        /** Create a job posting */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job detail */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload resumes to a job
         * @description Up to 10 PDFs per request, 5 MB each. Type is verified by `%PDF-` magic
         *     bytes, not by extension.
         *
         *     Files that store successfully appear in `uploaded` **even if parsing
         *     failed** — the record carries `parseStatus`. Only files rejected before
         *     storage appear in `rejected`. A request where everything is rejected
         *     still returns 201 with an empty `uploaded` array.
         *
         */
        post: operations["uploadResumes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/screen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score every parsed resume on this job
         * @description Synchronous. Budget 1-2 s per resume with summaries enabled; clients
         *     should allow at least 180 s.
         *
         *     Results are upserted on (jobId, resumeId), so re-screening replaces
         *     rather than appends. Scoring failure fails the request; summarization
         *     failure does not — it increments `summariesDegraded`.
         *
         */
        post: operations["screenJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ranked candidate list
         * @description Includes unscreened resumes with `screening: null`; those always sort
         *     last regardless of `order`.
         *
         */
        get: operations["listCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{resumeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Candidate detail including summary prose
         * @description `parsedText` is deliberately not returned.
         */
        get: operations["getCandidate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actuator/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Must return a response even when MongoDB is down.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example 665f1a2b3c4d5e6f70819201 */
        ObjectId: string;
        ErrorResponse: {
            error: {
                /**
                 * @description One of the codes in docs/03-API-CONTRACT.md. Never invent new ones.
                 * @enum {string}
                 */
                code: "VALIDATION_FAILED" | "MALFORMED_JSON" | "UNAUTHORIZED" | "INVALID_CREDENTIALS" | "FORBIDDEN" | "JOB_NOT_FOUND" | "RESUME_NOT_FOUND" | "EMAIL_ALREADY_REGISTERED" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_FILE_TYPE" | "TOO_MANY_FILES" | "BATCH_TOO_LARGE" | "NO_SCOREABLE_RESUMES" | "INTERNAL_ERROR" | "AI_SERVICE_UNAVAILABLE";
                message: string;
                /** @example c1a9f4e2b7d34a10 */
                traceId: string;
                details?: {
                    [key: string]: string;
                } | null;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            fullName: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthResponse: {
            token: string;
            /** Format: date-time */
            expiresAt: string;
            user: components["schemas"]["User"];
        };
        User: {
            id: components["schemas"]["ObjectId"];
            /** Format: email */
            email: string;
            fullName: string;
            /** @enum {string} */
            role: "RECRUITER";
            /** Format: date-time */
            createdAt?: string;
        };
        CreateJobRequest: {
            title: string;
            description: string;
            requiredSkills?: string[];
            location?: string | null;
        };
        Job: {
            id: components["schemas"]["ObjectId"];
            title: string;
            description: string;
            /** @description Normalized to lowercase, trimmed, de-duplicated. */
            requiredSkills: string[];
            location?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            resumeCount: number;
            screenedCount: number;
            /** @description Resumes with parseStatus EMPTY or FAILED */
            unreadableCount?: number;
            /** Format: date-time */
            lastScreenedAt?: string | null;
        };
        /** @description List projection — omits `description`. */
        JobSummary: {
            id: components["schemas"]["ObjectId"];
            title: string;
            location?: string | null;
            requiredSkills: string[];
            /** Format: date-time */
            createdAt: string;
            resumeCount: number;
            screenedCount: number;
        };
        JobSummaryPage: components["schemas"]["PageMeta"] & {
            content: components["schemas"]["JobSummary"][];
        };
        PageMeta: {
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
            totalPages: number;
        };
        /**
         * @description PARSED - text extracted.
         *     EMPTY  - opened fine but no text (scan / image-only). Not screened.
         *     FAILED - extraction threw (encrypted, corrupt). Not screened.
         *
         * @enum {string}
         */
        ParseStatus: "PARSED" | "EMPTY" | "FAILED";
        UploadedResume: {
            id: components["schemas"]["ObjectId"];
            candidateName: string;
            originalFilename: string;
            parseStatus: components["schemas"]["ParseStatus"];
            pageCount: number;
            /** Format: int64 */
            sizeBytes: number;
            /** Format: date-time */
            uploadedAt: string;
        };
        RejectedFile: {
            filename: string;
            /** @enum {string} */
            reason: "UNSUPPORTED_FILE_TYPE" | "PAYLOAD_TOO_LARGE";
        };
        UploadResponse: {
            uploaded: components["schemas"]["UploadedResume"][];
            rejected: components["schemas"]["RejectedFile"][];
        };
        ScreenResponse: {
            jobId: components["schemas"]["ObjectId"];
            screened: number;
            /** @description Resumes not in PARSED state */
            skipped: number;
            /** @description Scored but no summary */
            summariesDegraded: number;
            /** @example all-MiniLM-L6-v2@1110a24 */
            modelVersion: string;
            /** Format: int64 */
            durationMs: number;
            /** Format: date-time */
            screenedAt: string;
        };
        /** @description List projection — no prose. */
        ScreeningSummary: {
            score: number;
            /** Format: double */
            semanticScore: number;
            /** Format: double */
            skillScore: number;
            matchedSkills: string[];
            missingSkills: string[];
            summaryDegraded: boolean;
            /** Format: date-time */
            scoredAt: string;
        };
        ScreeningDetail: components["schemas"]["ScreeningSummary"] & {
            /** @description Null when summarization degraded. */
            summary?: string | null;
            strengths?: string[] | null;
            concerns?: string[] | null;
            modelVersion?: string;
            promptVersion?: string | null;
            weights?: components["schemas"]["Weights"];
        };
        Weights: {
            /**
             * Format: double
             * @example 0.7
             */
            semantic: number;
            /**
             * Format: double
             * @example 0.3
             */
            skill: number;
        };
        Candidate: {
            resumeId: components["schemas"]["ObjectId"];
            candidateName: string;
            candidateEmail?: string | null;
            originalFilename: string;
            parseStatus: components["schemas"]["ParseStatus"];
            /** Format: date-time */
            uploadedAt: string;
            /** @description Null when the resume has not been screened yet. */
            screening: components["schemas"]["ScreeningSummary"] | null;
        };
        CandidatePage: components["schemas"]["PageMeta"] & {
            content: components["schemas"]["Candidate"][];
        };
        CandidateDetail: {
            resumeId: components["schemas"]["ObjectId"];
            jobId: components["schemas"]["ObjectId"];
            jobTitle: string;
            candidateName: string;
            candidateEmail?: string | null;
            originalFilename: string;
            parseStatus: components["schemas"]["ParseStatus"];
            pageCount: number;
            /** Format: date-time */
            uploadedAt: string;
            /** @description Null when the resume has not been screened yet. */
            screening: components["schemas"]["ScreeningDetail"] | null;
        };
    };
    responses: {
        /** @description Validation failed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing, malformed, or expired token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource belongs to another recruiter */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        JobId: components["schemas"]["ObjectId"];
        /** @description 0-based */
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created, token issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid credentials. Wrong email and wrong password return the same
             *     code and message on purpose.
             *      */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated recruiter */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listJobs: {
        parameters: {
            query?: {
                /** @description 0-based */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of job summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummaryPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Created. `requiredSkills` is normalized (lowercased, trimmed,
             *     de-duplicated) so it may differ from what was sent.
             *      */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    uploadResumes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    files: string[];
                };
            };
        };
        responses: {
            /** @description Upload processed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A file exceeded the size limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many files in one request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    screenJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Screening finished */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description No scoreable resumes, or batch over the cap */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description ai-service unreachable or failed after one retry */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listCandidates: {
        parameters: {
            query?: {
                sort?: "score" | "name" | "uploadedAt";
                order?: "asc" | "desc";
                /** @description 0-based */
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                id: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of candidates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resumeId: components["schemas"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The candidate */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example UP */
                        status?: string;
                    };
                };
            };
        };
    };
}
