package com.screener.api.service;

import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import com.screener.api.dto.AiDtos.*;import com.screener.api.exception.ApiException;import com.screener.api.exception.ErrorCode;import com.screener.api.model.Job;import com.screener.api.model.Resume;import com.screener.api.repository.ResumeRepository;import java.time.Instant;import java.util.List;import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;import org.springframework.data.mongodb.core.BulkOperations;import org.springframework.data.mongodb.core.MongoTemplate;
class ScreeningServiceTest {
 private JobService jobs=mock(JobService.class);private ResumeRepository resumes=mock(ResumeRepository.class);private AiClient ai=mock(AiClient.class);private MongoTemplate mongo=mock(MongoTemplate.class);private BulkOperations bulk=mock(BulkOperations.class);private ScreeningService service;
 private final Job job=new Job("665f1a2b3c4d5e6f70819201","Backend","A sufficiently long job description for testing the screening workflow.",List.of("java"),null,"user",Instant.now(),Instant.now());
 @BeforeEach void setup(){service=new ScreeningService(jobs,resumes,ai,mongo,2);when(jobs.requireOwned(job.id(),"user")).thenReturn(job);}
 @Test void zeroParsedResumesNeverCallsAi(){when(resumes.findByJobIdAndParseStatus(any(),any())).thenReturn(List.of());assertCode(ErrorCode.NO_SCOREABLE_RESUMES);verifyNoInteractions(ai);}
 @Test void overCapNeverCallsAi(){when(resumes.findByJobIdAndParseStatus(any(),any())).thenReturn(List.of(resume("1"),resume("2"),resume("3")));assertCode(ErrorCode.BATCH_TOO_LARGE);verifyNoInteractions(ai);}
 @Test void scoringFailureWritesNothing(){when(resumes.findByJobIdAndParseStatus(any(),any())).thenReturn(List.of(resume("1")));when(ai.score(any())).thenThrow(new RuntimeException("down"));assertThatThrownBy(()->service.screen(job.id(),"user")).isInstanceOf(RuntimeException.class);verify(mongo,never()).bulkOps(any(BulkOperations.BulkMode.class),eq(com.screener.api.model.Screening.class));}
 @Test void degradedSummaryStillUpserts(){var r=resume("1");when(resumes.findByJobIdAndParseStatus(any(),any())).thenReturn(List.of(r));when(ai.score(any())).thenReturn(new ScoreResponse(List.of(new ScoreResult("1",80,.8,.8,List.of("java"),List.of())),"model",new Weights(.7,.3),1));when(ai.summarize(any())).thenReturn(new SummaryResponse("1",null,null,null,true,"timeout","v1","m"));when(mongo.bulkOps(any(BulkOperations.BulkMode.class),eq(com.screener.api.model.Screening.class))).thenReturn(bulk);when(bulk.upsert(any(),any())).thenReturn(bulk);when(bulk.execute()).thenReturn(null);when(resumes.countByJobId(job.id())).thenReturn(1L);var response=service.screen(job.id(),"user");assertThat(response.summariesDegraded()).isEqualTo(1);verify(bulk).upsert(any(),any());}
 private void assertCode(ErrorCode code){assertThatThrownBy(()->service.screen(job.id(),"user")).isInstanceOf(ApiException.class).satisfies(e->assertThat(((ApiException)e).code()).isEqualTo(code));}
 private Resume resume(String id){return new Resume(id,job.id(),"Candidate",null,id+".pdf",job.id()+"/"+id+".pdf","hash","resume text",1,Resume.ParseStatus.PARSED,null,100,"user",Instant.now());}
}
