package com.screener.api;

import static org.assertj.core.api.Assertions.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.fasterxml.jackson.databind.ObjectMapper;import com.screener.api.dto.AiDtos.*;import com.screener.api.model.Job;import com.screener.api.model.Resume;import com.screener.api.repository.JobRepository;import com.screener.api.repository.ResumeRepository;import com.screener.api.repository.ScreeningRepository;import com.screener.api.service.AiClient;import com.screener.api.service.ScreeningService;import java.time.Instant;import java.util.List;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.test.mock.mockito.MockBean;import org.springframework.data.mongodb.core.MongoTemplate;import org.springframework.http.MediaType;import org.springframework.test.context.DynamicPropertyRegistry;import org.springframework.test.context.DynamicPropertySource;import org.springframework.test.web.servlet.MockMvc;import org.testcontainers.containers.MongoDBContainer;import org.testcontainers.junit.jupiter.Container;import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers(disabledWithoutDocker=true)
@SpringBootTest @AutoConfigureMockMvc
class ApiIntegrationTest {
 @Container static MongoDBContainer mongo=new MongoDBContainer("mongo:7.0");
 @DynamicPropertySource static void properties(DynamicPropertyRegistry r){r.add("spring.data.mongodb.uri",mongo::getReplicaSetUrl);r.add("app.jwt.secret",()->"integration-secret-at-least-thirty-two-characters");r.add("app.ai.service-token",()->"test-token");r.add("app.upload.dir",()->"target/test-uploads");}
 @Autowired MockMvc mvc;@Autowired ObjectMapper json;@Autowired MongoTemplate template;@Autowired JobRepository jobs;@Autowired ResumeRepository resumes;@Autowired ScreeningRepository screenings;@Autowired ScreeningService screeningService;@MockBean AiClient ai;
 @Test void missingAndMalformedTokensUseEnvelope() throws Exception {mvc.perform(get("/api/jobs")).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.error.code").value("UNAUTHORIZED")).andExpect(jsonPath("$.error.traceId").isNotEmpty());mvc.perform(get("/api/jobs").header("Authorization","Bearer malformed")).andExpect(status().isUnauthorized()).andExpect(jsonPath("$.error.code").value("UNAUTHORIZED"));}
 @Test void passwordHashNeverAppearsAndOwnershipIsForbidden() throws Exception {String a=register("a@example.com"),b=register("b@example.com");String job=createJob(a);String detail=mvc.perform(get("/api/jobs/"+job).header("Authorization","Bearer "+b)).andExpect(status().isForbidden()).andExpect(jsonPath("$.error.code").value("FORBIDDEN")).andReturn().getResponse().getContentAsString();assertThat(detail).doesNotContain("passwordHash");mvc.perform(get("/api/auth/me").header("Authorization","Bearer "+a)).andExpect(status().isOk()).andExpect(content().string(org.hamcrest.Matchers.not(org.hamcrest.Matchers.containsString("passwordHash"))));}
 @Test void startupCreatesAllSixIndexes(){long total=template.indexOps("users").getIndexInfo().size()+template.indexOps("jobs").getIndexInfo().size()+template.indexOps("resumes").getIndexInfo().size()+template.indexOps("screenings").getIndexInfo().size();assertThat(total).isGreaterThanOrEqualTo(10);}
 @Test void rescreeningUpsertsInsteadOfDuplicating(){String user="665f1a2b3c4d5e6f70819299",jobId="665f1a2b3c4d5e6f70819298",resumeId="665f1a2b3c4d5e6f70819297";Instant now=Instant.now();jobs.save(new Job(jobId,"Backend","A sufficiently long backend engineering description for the database upsert integration test.",List.of("java"),null,user,now,now));resumes.save(new Resume(resumeId,jobId,"Candidate",null,"resume.pdf",jobId+"/"+resumeId+".pdf","hash","Java engineer",1,Resume.ParseStatus.PARSED,null,100,user,now));org.mockito.Mockito.when(ai.score(org.mockito.ArgumentMatchers.any())).thenReturn(new ScoreResponse(List.of(new ScoreResult(resumeId,80,.8,.8,List.of("java"),List.of())),"model",new Weights(.7,.3),1));org.mockito.Mockito.when(ai.summarize(org.mockito.ArgumentMatchers.any())).thenReturn(new SummaryResponse(resumeId,null,null,null,true,"disabled","v1","model"));screeningService.screen(jobId,user);Instant first=screenings.findByJobIdAndResumeId(jobId,resumeId).orElseThrow().scoredAt();screeningService.screen(jobId,user);var stored=screenings.findByJobId(jobId);assertThat(stored).hasSize(1);assertThat(stored.getFirst().scoredAt()).isAfterOrEqualTo(first);}
 private String register(String email)throws Exception{String body=mvc.perform(post("/api/auth/register").contentType(MediaType.APPLICATION_JSON).content("{\"email\":\""+email+"\",\"password\":\"password123\",\"fullName\":\"Test User\"}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return json.readTree(body).get("token").asText();}
 private String createJob(String token)throws Exception{String body=mvc.perform(post("/api/jobs").header("Authorization","Bearer "+token).contentType(MediaType.APPLICATION_JSON).content("{\"title\":\"Backend Engineer\",\"description\":\"A sufficiently long backend engineering description used for integration testing.\",\"requiredSkills\":[\"Java\"]}")).andExpect(status().isCreated()).andReturn().getResponse().getContentAsString();return json.readTree(body).get("id").asText();}
}
